name: Test content scripts on Workday

on:
    workflow_dispatch: # Manual Option
    schedule:
      - cron: '0 14 * * *' # Run at 06:00 PST (14:00 UTC) every day.
jobs:
  
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      # Build the extension
      - name: Install extension dependencies
        run: npm ci; cd __test__/react_content_scripts && npm ci --legacy-peer-deps
        working-directory: extension
      
      - name: Build extension
        run: npm run buildall
        working-directory: extension
      
      # Install dependencies
      - name: Install utils dependencies
        run: npm ci
        working-directory: backend/web_scraping/utils
      - name: Install test dependencies
        run: npm ci
        working-directory: backend/web_scraping/test_content_scripts
      
      # Test the extension
      - name: Run puppeteer script with virtual display
        run: xvfb-run -a node index.js
        env:
          SCU_USERNAME: ${{ secrets.SCU_USERNAME }}
          SCU_PASSWORD: ${{ secrets.SCU_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SNS_TOPIC_ARN: ${{ secrets.CONTENT_SCRIPTS_ERRORS_SNS }}
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        working-directory: backend/web_scraping/test_content_scripts

